apiVersion: v1
kind: Pod
metadata:
  name: my-app-prod-pod
  namespace: prod
spec:
  containers:
  - name: my-app-container
    image: my-app-image:latest
    command: ["/bin/sh", "-c"]
    args:
    - while true; do
        echo "Accessing production bucket...";
        gsutil ls gs://nisha-${formatdate("YYMM", timestamp())}-prod1;
        sleep 60;
      done

