apiVersion: v1
kind: Pod
metadata:
  name: my-app-staging-pod
  namespace: staging
spec:
  containers:
  - name: my-app-container
    image: my-app-image:latest
    command: ["/bin/sh", "-c"]
    args:
    - while true; do
        echo "Accessing staging bucket...";
        gsutil ls gs://nisha-${formatdate("YYMM", timestamp())}-staging1;
        sleep 60;
      done

